### ISSUE TITLE
Palpy Cython-related issues

### ISSUE THREAD

**Issue by rhea05** [Starlink/palpy#17]
Hi Palpy team! I'm dealing with a couple issues related to Cython that I was hoping someone could help resolve

This is the error I get when I try to pip install palpy with the most recent version of cython
![image](https://github.com/Starlink/palpy/assets/67562124/cbab2abe-b8cf-45bb-bb63-148e3fed88da)

When trying to build cython from source I got a decently longer error message:
![image](https://github.com/Starlink/palpy/assets/67562124/2fd18528-964f-4c6f-be66-474eebd75318)

I'm running on a Linux backend!

**Comment by timj** [comment]
I have a fix in #18

**Comment by rhiannonlynne** [comment]
I see the fix was merged yesterday .. could you please make a tag so it gets published on PyPI? (I'm getting what looks like the same error as above, today).

**Comment by timj** [comment]
1.8.3 is now on pypi and I made some wheels as well to make things a little easier.
